[dependencies]
"org.apache.maven.resolver:maven-resolver-api" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-spi" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-impl" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-util" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-connector-basic" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-transport-file" = "1.8.2"
"org.apache.maven.resolver:maven-resolver-transport-http" = "1.8.2"
"org.apache.maven:maven-resolver-provider" = "3.8.6"
"org.apache.maven:maven-core" = "3.8.6"
