[project]
flix = "0.32.0"
paths = ["src"]

[dependencies]
"org.apache.maven.resolver:maven-resolver-api".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-spi".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-impl".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-util".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-connector-basic".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-transport-file".mvn = "1.8.2"
"org.apache.maven.resolver:maven-resolver-transport-http".mvn = "1.8.2"
"org.apache.maven:maven-resolver-provider".mvn = "3.8.6"
"org.apache.maven:maven-core".mvn = "3.8.6"
